[package]
name = "cloud-entertainment/roact"
version = "1.4.1"
license = "Apache-2.0"
registry = "https://github.com/Cloud-Entertainment/wally-index"
realm = "shared"
exclude = ["wally.exe"]

[dependencies]